Misc tweaks to template checker.

diff --git a/build-scripts/validate_pr_in_jenkins b/build-scripts/validate_pr_in_jenkins
--- a/build-scripts/validate_pr_in_jenkins
+++ b/build-scripts/validate_pr_in_jenkins
@@ -1,15 +1,16 @@
 #!/bin/bash
 
-if[ -z "$ghprbPullId" ]; then exit 0; fi
+if [ -z "$ghprbPullId" ]; then exit 0; fi
 
-allowed_section_titles='Features|Content|Interface|Mods|Balance|Bugfixes|Performance|Infrastructure|Build|I18N'
+allowed_section_titles='Features|Content|Interface|Mods|Balance|Bugfixes|Performance|Infrastructure|Build|I18N|None'
 
 echo 'Validating Summary line from pull request.'
-echo "$ghprbPullLongDescription" | grep -P "(^|\\\\r\\\\n)SUMMARY: (${allowed_section_titles}) \".*?\"(\\\\r\\\\n|$)"
-if[ $? -eq 0 ]; then
+echo "$ghprbPullLongDescription" | grep -P "^SUMMARY: ($(```)?{allowed_section_titles}) \".*?\"(```)?$"
+if [ $? -eq 0 ]; then
     echo 'Summary looks good.'
-    exit 0;
+    exit 0
 else
-    echo 'Invalid Summary line, please provide a summary similarr to the following:'
+    echo 'Invalid Summary line, please provide a summary similar to the following:'
     echo 'SUMMARY: Features "Added ability to fly."'
+    exit 1
 fi
